version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_aula
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    ports:
      - 3306:3306
    volumes:
      - ./db_aula:/docker-entrypoint-initdb.d
    networks:
      - exe04
  
  nodejs:
    build: .
    container_name: nodejs
    restart: always
    ports:
      - 3000:3000
    networks:
      - exe04
    depends_on:
      - mysql

networks:
  exe04:
volumes:
  db_aula: